#!/usr/bin/env bash
rm -r ./documentation/
mkdir ./documentation/
# Generate rst docs using the full project and ignoring all test files
sphinx-apidoc -F -H 'Machine Learning' -A 'Corbin Baldwin' -o ./documentation . *Test*
cd ./documentation/
# Uncomment the the autogenerated system path edits
sed -i "s/# import os/import os/" ./conf.py ./conf.py
sed -i "s/# import sys/import sys/" ./conf.py ./conf.py
sed -i "s/# sys.path.insert/sys.path.insert/" ./conf.py ./conf.py
# Make the html files
make html
cd ../